# Generated by Django 5.0.6 on 2024-06-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Portfolio',
        ),
    ]
