# Generated by Django 4.2.13 on 2024-06-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_todo_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('medium', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('strong_sides_and_skills', models.TextField(blank=True, null=True)),
                ('programming_knowledge', models.TextField(blank=True, null=True)),
                ('tools_knowledge', models.TextField(blank=True, null=True)),
                ('communication_skills', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
